[CS] Fix typo, adding sentence for garage door
home-assistant/intents pull request #1061
Opened 2023-02-19 22:02 UTC by motylu

Fix typo, adding commonly used sentence for open/close garage door

2023-02-19 22:45 UTC, schizza requested changes
Files needs to be fixed to follow rules in https://developers.home-assistant.io/docs/documenting/yaml-style-guide/

Everything in cover files is broken since #1027

Tests are auto-generated - needs to be fixed.
homeassistant_HassTurnOn/off files have redundant cover sentences.

2023-02-19 22:54 UTC, schizza commented on tests/cs/homeassistant_HassTurnOff.yaml
>        slots:
toto už nepatří do homeassistant_HassTurnOff/On, ale do cover_
stejně tak zbytek vět obsluhující domain:cover

2023-02-19 22:56 UTC, schizza commented on tests/cs/cover_HassTurnOff.yaml
>    - sentences:
Celý soubor je po migraci totálně rozbitý. Je potřeba ho celý upravit. A taky odpověď garage zavřena není úplně ono :/

2023-02-19 22:56 UTC, schizza commented on tests/cs/cover_HassTurnOn.yaml
> +      - otevři garážová vrata
stejně tak tady. Celý soubor se musí opravit: https://developers.home-assistant.io/docs/documenting/yaml-style-guide/

2023-02-19 22:58 UTC, schizza commented on tests/cs/homeassistant_HassTurnOff.yaml
> +      - zavři vrata od garáže
tady je test na garaž zbytečný, patří do cover_HassTurnOff

2023-02-20 10:40 UTC, motylu commented on tests/cs/homeassistant_HassTurnOff.yaml
>        slots:
odstraněno...

2023-02-20 10:41 UTC, motylu commented on tests/cs/cover_HassTurnOff.yaml
>    - sentences:
Pokusil jsem se o opravu, ale nejsem žádný moc zkušený programátor, spíš nadšený uživatel :--)

2023-02-20 10:42 UTC, motylu commented on tests/cs/homeassistant_HassTurnOff.yaml
> +      - zavři vrata od garáže
přesunuto...

2023-02-20 11:03 UTC, schizza requested changes
Takto neee. 
Navíc, úprav je moc. Vždy je lepší dělat úpravy po malých kouscích, atˇse to líp kontroluje.
Navíc takhle nic neodpovídá pravidlům pro parser. 
Takže tento commit odvolat.

2023-02-20 11:03 UTC, schizza commented on sentences/cs/_common.yaml
> +  ktere: "(kter(á|é) | jak(é|á))"
_common.yaml byl zcela správně, až na typo.
Mezi `|` nesmí být mezery, pokud ji tam neočekáváme. Jinak dochází ke zdvojení mezer.

2023-02-20 11:03 UTC, schizza commented on sentences/cs/climate_HassClimateSetTemperature.yaml
> +          - "(<nastavit> | <zvysit> | <ztlumit> | <zmenit>) teplotu [<area>] na <teplota>"
No whitespaces around `|`

2023-02-20 13:04 UTC, schizza commented on sentences/cs/homeassistant_HassTurnOff.yaml
> +            - fan
- cover
- fan 

jsou tu zbytečné, nemají stejné volání, tudíž by neměli padat do obecého homeassistant_HassTurnOff, ale nechate je tu asi můžem

2023-02-20 13:05 UTC, schizza commented on responses/cs/HassTurnOff.yaml
> +      cover_area: "Stínění v {{ slots.area }} zavřeno"
Takto nebude správně odpovídat na jiné covers!  Třeba rolety, žaluzie. Vžd řekne stínění.

2023-02-20 15:49 UTC, schizza approved these changes
Ještě by to tedy chtělo udělat response pro každou `device_class`

nebo jednotnout odpověď s if ... else

2023-02-20 15:50 UTC, merged