[WIP][RU] Initial commit on GetState
home-assistant/intents pull request #1115
Opened 2023-02-24 09:21 UTC by HepoH3

Tests with responses for 'all' and 'any' states are failed for now.

2023-02-24 09:48 UTC, HepoH3 commented
@synesthesiam, can you have a glance at this error? When I run tests from codespaces everything fine.

It says that on sentence "Задернута ли левая штора?" should be responsed "Нет, off". First of all, there is no "Off" state for cover. Moreover, to make things work, I translated states, so there is no even `closed` state in `ru` domain.
`in/out filter` will cast first word of sentence (`задернута`) into `закрыта`:

```yaml
      - in: "закрыт[а|о|ы|ой|ая|ые|ую]|задернут[а|о|ы|ой|ая|ые|ую]|поднят[а|о|ы|ой|ая|ые|ую]"
        out: "закрыта"
```

so there is sentense `задернута ли левая штора`, which parsed by: 

```yaml
  "{cover_states:state} [ли] <name> [<area>]"
```

while entity `Левая штора` has following attributes:

```yaml
  - name: "Левая штора"
    id: "cover.curtain_left"
    area: "living_room"
    state: "открыта"
    attributes:
      device_class: curtain
```

Apparantly it's state not `закрыта`, but `открыта` instead. So response should be `Нет, открыта` (no, closed).

UPD. okay, so I've merged main branch from upstream and get this error again, so problem appeared in some commit after 8310e374. The asserted state still confuse me, maybe it's a bug?

2023-03-14 05:42 UTC, skynetua commented
This is probably because this duplicate entity in fixtures:
```
  - name: "Лев(ая|ую|ой) (занавеск|штор)(а|у|ы)"
     id: "cover.curtain_left"
     area: "living_room"
```

It has no device_class and state so off by default.

2023-03-14 05:49 UTC, skynetua requested changes

2023-03-14 05:49 UTC, skynetua commented on tests/ru/_fixtures.yaml
> +    id: "cover.curtain_left"
Merge this with entity above

2023-03-14 07:40 UTC, HepoH3 commented on tests/ru/_fixtures.yaml
> +    id: "cover.curtain_left"
> This is probably because this duplicate entity in fixtures:

That's it, thank you!

2023-03-14 07:46 UTC, skynetua commented on sentences/ru/_common.yaml
> +      - in: "закрыт[а|о|ы|ой|ая|ые|ую]|задернут[а|о|ы|ой|ая|ые|ую]|поднят[а|о|ы|ой|ая|ые|ую]"
Поднята is wrong here

2023-03-14 08:09 UTC, HepoH3 commented on sentences/ru/_common.yaml
> +      - in: "закрыт[а|о|ы|ой|ая|ые|ую]|задернут[а|о|ы|ой|ая|ые|ую]|поднят[а|о|ы|ой|ая|ые|ую]"
But it's a cover device states. If we talk about shutter, or blinds, we could have a sentence "подняты ли жалюзи" for example.

2023-03-14 08:14 UTC, skynetua commented on sentences/ru/_common.yaml
> +      - in: "закрыт[а|о|ы|ой|ая|ые|ую]|задернут[а|о|ы|ой|ая|ые|ую]|поднят[а|о|ы|ой|ая|ые|ую]"
Yes, but it's added for both out states "открыта" and "закрыта", so change it to опущена

2023-03-14 08:18 UTC, HepoH3 commented on sentences/ru/_common.yaml
> +      - in: "закрыт[а|о|ы|ой|ая|ые|ую]|задернут[а|о|ы|ой|ая|ые|ую]|поднят[а|о|ы|ой|ая|ые|ую]"
Oh, you're right! Thanks again!

2023-03-14 08:55 UTC, skynetua commented on sentences/ru/_common.yaml
> +      - in: "закрыт[а|о|ы|ой|ая|ые|ую]|задернут[а|о|ы|ой|ая|ые|ую]|поднят[а|о|ы|ой|ая|ые|ую]"
Np

2023-03-14 08:56 UTC, skynetua approved these changes

2023-03-14 08:57 UTC, merged