[DE] added new phrases for lock_states
home-assistant/intents pull request #1243
Opened 2023-03-15 17:32 UTC by mymyke

added the following phrases for unlocked
"versperrt", "abgesperrt" or "zugesperrt"
added the following phrases for unlocked:
"nicht verriegelt","nicht verperrt","nicht abgesperrt", "nicht zugesperrt","entsperrt","offen"

Added tests for the new phrases

2023-03-15 17:52 UTC, mymyke commented on sentences/de/_common.yaml
> +      - in: "(nicht (([ab|zu]ge|ver)schlossen|verriegelt|((ab|zu)ge|ver)sperrt)|entriegelt|entsperrt)"
Should now additionally accept phrases like:
nicht verriegelt
nicht verperrt
nicht abgesperrt
nicht zugesperrt
entsperrt

2023-03-15 20:40 UTC, mib1185 requested changes
Hi @mymyke 
thanks for this contribution. I've left some comments.
thx 👍

2023-03-15 20:40 UTC, mib1185 commented on sentences/de/_common.yaml
> +      - in: "(nicht (([ab|zu]ge|ver)schlossen|verriegelt|((ab|zu)ge|ver)sperrt)|entriegelt|entsperrt)"
```suggestion
      - in: "(nicht (([ab|zu]ge|ver)(schlossen|sperrt)|verriegelt)|ent(riegelt|sperrt))"
```
this allows:

- nicht abgeschlossen
- nicht zugeschlossen
- nicht geschlossen
- nicht verschlossen
- nicht abgesperrt
- nicht zugesperrt
- nicht gesperrt
- nicht versperrt
- nicht verriegelt
- entriegelt
- entsperrt

2023-03-15 20:40 UTC, mib1185 commented on sentences/de/_common.yaml
> +      - in: "(([ab|zu]ge|ver)schlossen|verriegelt|((ab|zu)ge|ver)sperrt)"
```suggestion
      - in: "(([ab|zu]ge|ver)(schlossen|sperrt)|verriegelt)"
```
this allows:
- abgeschlossen
- zugeschlossen
- geschlossen
- verschlossen
- abgesperrt
- zugesperrt
- gesperrt
- versperrt
- verriegelt

2023-03-15 20:40 UTC, mib1185 commented on tests/de/lock_HassGetState.yaml
> +      - "Sind irgendwelche Türen entsperrt?"
please add test for "nicht verriegelt"

2023-03-15 20:40 UTC, mib1185 commented on tests/de/lock_HassGetState.yaml
> +      - "Ist die Haustür versperrt?"
please add tests for "gesperrt" and "verriegelt"

2023-04-06 14:10 UTC, mib1185 commented on tests/de/lock_HassGetState.yaml
> +      - "Ist die Haustür versperrt?"
```suggestion
      - "Ist die Haustür gesperrt?" 
      - "Ist die Haustür verriegelt?"
      - "Ist die Haustür versperrt?"
```

2023-04-06 14:15 UTC, mib1185 commented on tests/de/lock_HassGetState.yaml
> +      - "Sind irgendwelche Türen nicht verriegelt?"
```suggestion
```

2023-04-06 14:25 UTC, mib1185 approved these changes

2023-04-06 14:25 UTC, merged