Aligned Danish version of _common.yaml with English version
home-assistant/intents pull request #1252
Opened 2023-03-18 20:17 UTC by DocDoo

Hoping to be able to contribute with Danish translations of sentences, but first time user of Code Spaces so not quite sure if everything went to plan.

2023-03-18 20:21 UTC, fadamsen commented
Hi @DocDoo! This looks good, I’ll take a closer look when I’m at a computer, might not be until tomorrow, though.

2023-03-25 10:49 UTC, fadamsen commented
Hi @DocDoo! Life happened, so I'm only looking at this now. I'll post a review in a bit, but note that you'll also need to sign a CLA before this can be merged, as instructed in the comment [here](https://github.com/home-assistant/intents/pull/1252#issuecomment-1474981245).

2023-03-25 11:21 UTC, DocDoo commented
> Hi @DocDoo! Life happened, so I'm only looking at this now. I'll post a review in a bit, but note that you'll also need to sign a CLA before this can be merged, as instructed in the comment [here](https://github.com/home-assistant/intents/pull/1252#issuecomment-1474981245).

👍, no problem, Life does indeed happen🙂
Regarding the CLA, the cla-bot reached out and we got the agreement signed by me, so it looks (to me) like this is already in order, but let me know if this is not the case.
![image](https://user-images.githubusercontent.com/46087270/227714476-b7b46c78-bcfe-4a89-8cbe-e97ce063959a.png)

2023-03-25 11:22 UTC, fadamsen commented
Ah, I missed that! I thought there would be a comment, but all is well.

2023-03-25 11:57 UTC, fadamsen requested changes
Okay, quite a few comments here, but mostly small stuff, such as adding more alternatives and word endings to align with the existing translations.

A couple of words are, I think, not very natural to use, especially "påvist" and "tilstedeværende" are used in many places where, to me, they don't make sense. It's hard to draw the line between being accommodating and making things to complicated, but I tried.

Do let me know if there is anything in particular you disagree with and we can discuss.

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: (minimum|mindste|laveste)
```suggestion
      - in: (lavest[e]|mindst[e]|minimal[e]|minimum)
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: markise[rne]
```suggestion
      - in: markise[(n|r|rne)]
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: persienne[rne]
```suggestion
      - in: persienne[(n|r|rne)]
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: gardin[erne]
```suggestion
      - in: gardin[(et|er|erne)]
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: dør[ene]
```suggestion
      - in: dør[(en|e|ene)]
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: garageport[ene]
```suggestion
      - in: garage(dør|port)[(en|e|ene)]
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: låge[rne]
```suggestion
      - in: låge[(en|r|rne)]
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: skærm[ene]
This is closer to "persienne" or "rullegardin" in Danish.

```suggestion
      - in: (persienne[(en|r|rne)]|rullegardin[(et|er|erne)])
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: skodde[rne]
```suggestion
      - in: skodde[(n|r|rne)]
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: vindue[rne]
```suggestion
      - in: vindue[(t|r|rne)]
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: ventilator[ene]
```suggestion
      - in: ventilator([en|erne])
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: afbryder[ene]
```suggestion
      - in: (afbryder[(en|ne)]|kontakt[(en|erne)])
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "(detekteret|påvist|tilstedeværende)"
I don't think "påvist" and "tilstedeværende" make sense, semantically, for this.

```suggestion
      - in: "(detekteret|fundet|registreret)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "(ikke detekteret|ikke påvist|fraværende)"
```suggestion
      - in: "(ikke detekteret|ikke fundet|ikke registreret)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "koldt"
```suggestion
      - in: "kold[t]"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "(detekteret|påvist|tilstedeværende)"
```suggestion
      - in: "(detekteret|fundet|registreret)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "(ikke detekteret|ikke påvist|fraværende)"
```suggestion
      - in: "(ikke detekteret|ikke fundet|ikke registreret)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "varmt"
```suggestion
      - in: "varm[t]"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "normalt"
```suggestion
      - in: "normal[t]"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "normalt"
```suggestion
      - in: "normal[t]"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "detekteret"
```suggestion
      - in: "(detekteret|registreret)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "ikke detekteret"
```suggestion
      - in: "(ikke detekteret|ikke registreret)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "vådt"
```suggestion
      - in: "våd[t]"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "tørt"
```suggestion
      - in: "tør[t]"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "(detekteret|påvist)"
```suggestion
      - in: "(detekteret|registreret)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "(ikke detekteret|ikke påvist)"
```suggestion
      - in: "(ikke detekteret|ikke registreret)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "(detekteret|påvist|tilstedeværende)"
```suggestion
      - in: "(detekteret|registreret)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "(ikke detekteret|ikke påvist|fraværende)"
```suggestion
      - in: "(ikke detekteret|ikke registreret)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "tilkoblet"
```suggestion
      - in: "(koblet til|sat i)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "frakoblet"
```suggestion
      - in: "(ikke koblet til|ikke sat i)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "(væk|fraværende)"
```suggestion
      - in: "(fraværende|ikke hjemme|ude)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "fundet"
```suggestion
      - in: "(detekteret|fundet|registreret)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "intet fundet"
```suggestion
      - in: "(ikke detekteret|ikke fundet|ikke registreret)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "(stoppet|deaktiveret)"
```suggestion
      - in: "kører ikke"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "(kører|aktiveret)"
I don't think "aktiveret" makes sense for this.

```suggestion
      - in: "kører"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "farlig"
```suggestion
      - in: "(farlig|usikker)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "sikker"
```suggestion
      - in: "(sikker|ufarlig)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "(detekteret|påvist|tilstedeværende)"
```suggestion
      - in: "(detekteret|fundet|registreret)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "(ikke detekteret|ikke påvist|fraværende)"
```suggestion
      - in: "(ikke detekteret|ikke fundet|ikke registreret)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "(detekteret|påvist|tilstedeværende)"
```suggestion
      - in: "(detekteret|registreret)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "(ikke detekteret|ikke påvist|fraværende)"
```suggestion
      - in: "(ikke detekteret|ikke registreret)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "(detekteret|pillet ved)"
```suggestion
      - in: "(detekteret|pillet ved|registreret)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "(ikke detekteret|urørt)"
```suggestion
      - in: "(ikke detekteret|ikke pillet ved|ikke registreret)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "(detekteret|vibrerer)"
```suggestion
      - in: "(detekteret|registreret|vibrerer)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "(ikke detekteret|vibrerer ikke)"
```suggestion
      - in: "(ikke detekteret|ikke registreret|vibrerer ikke)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
>    garagedør: "garagedør[(en|e|ene)]"
Both "garagedør" and "garageport" represent the same device class, so I don't think they need to be treated as separate expansion rules.

```suggestion
  garagedør: "garage(dør|port)[(en|e|ene)]"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +  garageport: "garageport[(en|e|ene)]"
Combined with "garagedør" above.

```suggestion
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +  - "vær så venlig"
```suggestion
  - "venligst"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +  - "vil du"
```suggestion
  - "vil du"
  - "vær så venlig"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "åben"
```suggestion
      - in: "(åben[t]|åbne[t])"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: lys[ene]
```suggestion
      - in: lys[(et|ene)]
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "åben"
```suggestion
      - in: "(åben[t]|åbne[t])"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "åben"
```suggestion
      - in: "(åben[t]|åbne[t])"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "åben"
```suggestion
      - in: "(åben[t]|åbne[t])"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "ulåst"
```suggestion
      - in: "(låst op|ulåst)"
```

2023-03-25 11:57 UTC, fadamsen commented on sentences/da/_common.yaml
> +      - in: "åben"
```suggestion
      - in: "(åben[t]|åbne[t])"
```

2023-03-30 14:22 UTC, fadamsen commented
All right, I'm merging my suggestions so we can get this closed.

2023-03-30 14:26 UTC, fadamsen commented on sentences/da/_common.yaml
> +  - "vær så venlig"
```suggestion
```

2023-03-30 14:30 UTC, fadamsen approved these changes

2023-03-30 14:33 UTC, merged

2023-03-30 14:33 UTC, fadamsen commented
Thank you for the help, @DocDoo!

2023-03-30 14:35 UTC, DocDoo commented
> All right, I'm merging my suggestions so we can get this closed.

Yeah, sorry about not getting back to you @fadamsen , but now I got caught up in lot of other personal stuff. Thanks for pushing this through and I will take a look at your comments and suggestions which are very reasonable and come with any further comments. I'm also trying to get started in providing Danish translations of the sentences for "Lock", but struggling a bit as I also need to create the relevant files in the folder for the Danish language files. I think it has to do with me not entirely understanding how tests fit together with sentences, but I'll think some more about it and will possibly ask you for help if I don't end up figuring it out myself :-)

2023-03-30 14:40 UTC, fadamsen commented
No worries, I know how it is!