DE translation brightness_level
home-assistant/intents pull request #1279
Opened 2023-04-07 14:15 UTC by mymyke

Added brightness_level for DE language
Now one should be able to set brightnes to min and max in german. 

Added Translation for turquoise and Pink

2023-04-15 15:21 UTC, mib1185 requested changes
Hi @mymyke 
thanks for this contribution 👍 
There are some comments from my side, further the tests are failing, please fix this

2023-04-15 15:21 UTC, mib1185 commented on sentences/de/light_HassLightSet.yaml
> +          - "<setzen> [[[die] Helligkeit [von|von der|von den|der] ]| [die|das]] <name> auf [die|das] {brightness_level:brightness}  [ein]"
we can use the `<von_dem>` expansion rule here, further the `<name>` rule does already include articels

2023-04-15 15:21 UTC, mib1185 commented on sentences/de/_common.yaml
> +      - in: (max|[maximale|höchste|volle] (Helligkeit|Stufe) |maximum)
```suggestion
      - in: (max|[maximale|höchste|volle] (Helligkeit|Stufe)|maximum)
```

2023-04-15 15:21 UTC, mib1185 commented on sentences/de/_common.yaml
> +      - in: (minimum|minimale|niedrigste)
why not also use `Helligkeit|Stufe` here?

2023-04-15 15:21 UTC, mib1185 commented on tests/de/light_HassLightSet.yaml
after the changes above, please add a test sentences for every possible variant, also for the "set minimum" sentences

2023-04-21 19:29 UTC, mymyke commented on sentences/de/_common.yaml
> +        out: "turquoise"
I removed that

2023-04-21 19:30 UTC, mymyke commented on tests/de/light_HassLightSet.yaml
Tests were added now

2023-05-10 19:44 UTC, mib1185 requested changes
Hi @maddox 
sorry for late review, but busy days 🙁 
After some thought about this PR, I've added some new comments

2023-05-10 19:44 UTC, mib1185 commented on sentences/de/light_HassLightSet.yaml
> +          - "[die] Helligkeit [von|<von_dem>] <name> auf [die|das] {brightness_level:brightness} <setzen>"
```suggestion
          - "<setzen> [[die] Helligkeit [<von_dem>]] <name> auf [die|das] {brightness_level:brightness}  [ein]"
          - "[die] Helligkeit [<von_dem>] <name> auf [die|das] {brightness_level:brightness} <setzen>"
```

the expansion rule `<von_dem>` already covers "von" , "von dem" and "vom"

2023-05-10 19:44 UTC, mib1185 commented on sentences/de/_common.yaml
> +      - in: (max|(maximale|höchste|volle) (Helligkeit|Stufe)|maximum)
```suggestion
      - in: (max[(imale|imum)]|höchste|volle)
```
Sorry, but after some thought I'm think we should remove the `(Helligkeit|Stufe)` here and adjust the sentence definitions accordingly to create meaningful sentences. the same counts for the minimum values below.

2023-06-01 19:10 UTC, mib1185 commented on tests/de/light_HassLightSet.yaml
> +      - das Schlafzimmerlampe auf volle Helligkeit ändern
```suggestion
      - Stelle die Schlafzimmerlampe auf maximum
      - Stelle die Schlafzimmerlampe auf das maximum
      - Stelle die Schlafzimmerlampe auf die höchste Helligkeit
      - Stelle die Schlafzimmerlampe auf die höchste Stufe ein
      - Stelle die Schlafzimmerlampe auf das maximum ein
      - Stelle die Schlafzimmerlampe auf höchste Helligkeit
      - Stelle die Schlafzimmerlampe auf höchste Stufe ein
      - Stelle die Schlafzimmerlampe auf maximum ein
      - Stelle Helligkeit der Schlafzimmerlampe auf maximum
      - Stelle die Helligkeit der Schlafzimmerlampe auf maximum
      - Stelle die Helligkeit der Schlafzimmerlampe auf das maximum
      - Stelle die Helligkeit der Schlafzimmerlampe auf die höchste Stufe
      - Stelle die Helligkeit der Schlafzimmerlampe auf die höchste Stufe ein
      - Stelle die Helligkeit der Schlafzimmerlampe auf das maximum ein
      - Stelle die Helligkeit der Schlafzimmerlampe auf maximum
      - Stelle die Helligkeit der Schlafzimmerlampe auf höchste Stufe
      - Stelle die Helligkeit der Schlafzimmerlampe auf höchste Stufe ein
      - Stelle die Helligkeit der Schlafzimmerlampe auf maximum ein
      - Stelle Helligkeit von der Schlafzimmerlampe auf die höchste Stufe ein
      - Stelle Helligkeit von der Schlafzimmerlampe auf maximale Stufe ein
      - Helligkeit der Schlafzimmerlampe auf maximum stellen
      - die Helligkeit der Schlafzimmerlampe auf maximum stellen
      - die Helligkeit der Schlafzimmerlampe auf das maximum stellen
      - die Helligkeit der Schlafzimmerlampe auf die höchste Stufe stellen
      - die Helligkeit von der Schlafzimmerlampe auf maximum stellen
      - die Helligkeit von der Schlafzimmerlampe auf höchste Stufe stellen
      - die Helligkeit von der Schlafzimmerlampe auf die höchste Stufe stellen
      - Ändere die Helligkeit von der Schlafzimmerlampe auf die maximale Helligkeit
      - Veränder die Helligkeit von der Schlafzimmerlampe auf die höchste Stufe
      - das Schlafzimmerlampe auf volle Helligkeit ändern
```

2023-06-01 19:10 UTC, mib1185 commented on tests/de/light_HassLightSet.yaml
> +      - die Helligkeit der Schlafzimmerlampe auf das Minimum stellen.
```suggestion
      - Stelle die Schlafzimmerlampe auf minimum
      - Stelle die Schlafzimmerlampe auf das minimum
      - Stelle die Schlafzimmerlampe auf die niedrigste Helligkeit
      - Stelle die Schlafzimmerlampe auf die niedrigste Stufe ein
      - Stelle die Schlafzimmerlampe auf das minimum ein
      - Stelle die Schlafzimmerlampe auf niedrigste Helligkeit
      - Stelle die Schlafzimmerlampe auf niedrigste Stufe ein
      - Stelle die Schlafzimmerlampe auf minimum ein
      - Stelle Helligkeit der Schlafzimmerlampe auf minimum
      - Stelle die Helligkeit der Schlafzimmerlampe auf minimum
      - Stelle die Helligkeit der Schlafzimmerlampe auf das minimum
      - Stelle die Helligkeit der Schlafzimmerlampe auf die niedrigste Stufe
      - Stelle die Helligkeit der Schlafzimmerlampe auf die niedrigste Stufe ein
      - Stelle die Helligkeit der Schlafzimmerlampe auf das minimum ein
      - Stelle die Helligkeit der Schlafzimmerlampe auf minimum
      - Stelle die Helligkeit der Schlafzimmerlampe auf niedrigste Stufe
      - Stelle die Helligkeit der Schlafzimmerlampe auf niedrigste Stufe ein
      - Stelle die Helligkeit der Schlafzimmerlampe auf minimum ein
      - Stelle Helligkeit von der Schlafzimmerlampe auf die niedrigste Stufe ein
      - Stelle Helligkeit von der Schlafzimmerlampe auf niedrigste Stufe ein
      - Helligkeit der Schlafzimmerlampe auf minimum stellen
      - die Helligkeit der Schlafzimmerlampe auf minimum stellen
      - die Helligkeit der Schlafzimmerlampe auf das minimum stellen
      - die Helligkeit der Schlafzimmerlampe auf die niedrigste Stufe stellen
      - die Helligkeit von der Schlafzimmerlampe auf minimum stellen
      - die Helligkeit von der Schlafzimmerlampe auf niedrigste Stufe stellen
      - die Helligkeit von der Schlafzimmerlampe auf die niedrigste Stufe stellen
      - Ändere die Helligkeit von der Schlafzimmerlampe auf die niedrigste Helligkeit
      - Veränder die Helligkeit von der Schlafzimmerlampe auf die niedrigste Stufe
      - das Schlafzimmerlampe auf niedrigste Helligkeit ändern
```

2023-06-01 19:24 UTC, mib1185 approved these changes
LGTM, thx @mymyke 👍

2023-06-01 19:24 UTC, merged