[ar] cover_HassTurnOff
home-assistant/intents pull request #1281
Opened 2023-04-07 14:59 UTC by Natfaji

2023-04-07 17:52 UTC, Ahmed-farag36 commented
انا كنت خلصت دي!!
غيرتها ليه؟

2023-04-07 19:06 UTC, Natfaji commented
انا خلت قبلك أصلا
![image](https://user-images.githubusercontent.com/46685769/230663686-9071372c-e34a-4e42-9f1b-a5647c80fd1f.png)

2023-04-07 19:37 UTC, Ahmed-farag36 commented
ماشي معلش ما شوفتش أن فيه pull request مفتوح ☺️

2023-04-07 19:41 UTC, Ahmed-farag36 commented on sentences/ar/cover_HassTurnOff.yaml
> +          - "<close> {cover_classes:device_class} [<in>] <area>"
خلى "ال" علشان ممكن نقول "اقفل الستارة فى المطبخ" أو "اقفل ستارة المطبخ"

2023-04-07 19:56 UTC, Natfaji commented on sentences/ar/cover_HassTurnOff.yaml
> +          - "<close> {cover_classes:device_class} [<in>] <area>"
انا كان بدي اضيف "ال" في ملف "common_" 
![image](https://user-images.githubusercontent.com/46685769/230669529-d5b2ed60-c7f3-437e-99ec-bc9302d689ab.png)

2023-04-07 20:47 UTC, Ahmed-farag36 commented on sentences/ar/cover_HassTurnOff.yaml
> +          - "<close> {cover_classes:device_class} [<in>] <area>"
تمام خلينا نعدلها فى ملف `common_` ونظبط ملف ال **test** هنا قبل ما ن merge

2023-04-08 21:52 UTC, Ahmed-farag36 commented on responses/ar/HassTurnOn.yaml
>        scene: "تم التفعل"
```suggestion
      scene: "تم التفعيل"
```

2023-04-08 23:11 UTC, Ahmed-farag36 requested changes
please add the response to all tests

2023-04-08 23:11 UTC, Ahmed-farag36 commented on tests/ar/cover_HassTurnOff.yaml
> +    # response: "Closed garage"
add the response

2023-04-09 23:41 UTC, Ahmed-farag36 approved these changes

2023-04-09 23:42 UTC, merged