Add Support for further German Sentences for the Light Domain
home-assistant/intents pull request #1458
Opened 2023-07-23 12:10 UTC by Johnson145

2023-10-15 19:06 UTC, Johnson145 commented
@easterapps @mib1185 May I kindly ask for a review on this PR as well?

2023-10-18 12:03 UTC, kroimon approved these changes
Sounds good to me, I like to give short, robotic commands to voice assistants sometimes 😅 German efficiency, I guess...

2023-10-18 14:33 UTC, Johnson145 commented
@kroimon Thanks! May I ask you to merge the PR? I think I can't do it on my own even though you have approved it already.

2023-10-19 17:02 UTC, mib1185 requested changes
HI @Johnson145 
thanks for these additions 👍  just one comment about tests

2023-10-19 17:02 UTC, mib1185 commented on tests/de/light_HassLightSet.yaml
We need some more tests to get all new possible permutations covered

2023-10-19 17:40 UTC, Johnson145 commented on tests/de/light_HassLightSet.yaml
I added new test sentences and slightly modified the general syntax again to match all of the new tests. Would be great, if you can review again. Let me know if you're still missing something.

2023-12-09 14:48 UTC, mib1185 requested changes
HI @Johnson145 
overall I think this looks pretty well, but would be great we could have this logic also for setting a color. Thx 👍

2023-12-27 15:21 UTC, Johnson145 commented
@mib1185 I've just extended the PR to cover similar sentences for changing the color of a light. Looking forward to a final review.

2024-02-03 19:48 UTC, Johnson145 commented
@mib1185 Updated the branch one more time based on the `main`. I guess you're doing this in your freetime, too, and I don't want to bother you too much, but can you please have another look whether we can merge this by now?

2024-02-03 22:53 UTC, mib1185 approved these changes
Hi @Johnson145 
that's correct, this is all within my spare time 😉 
This PR looks good, thanks for this 👍

2024-02-03 22:53 UTC, merged