[IT] Italian Support
home-assistant/intents pull request #157
Opened 2022-12-27 12:10 UTC by auanasgheps

Hi there,
Here's my work for the Italian translation.

Fixes #62 

I'd like to be the leader of this language. I'm a daily user of Home Assistant and have translated dozens of projects.

2022-12-27 23:54 UTC, xraver commented
Sorry I didn't see your work... 
we can collaborate... i've prepared a pull request... we can merge them

2022-12-28 00:03 UTC, auanasgheps commented
@xraver I opened the PR first, so what we do?

2022-12-28 00:05 UTC, xraver commented
You have the Priority
I can cancel mine and work with you merging mine with yours. Does it work
for you?

Il Mar 27 Dic 2022, 19:03 Oliver Cervera ***@***.***> ha
scritto:

> @xraver <https://github.com/xraver> I opened the PR first, so what we do?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/home-assistant/intents/pull/157#issuecomment-1366269442>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALJM7A3KFVCW2YPERIZEB2LWPN7WRANCNFSM6AAAAAATKL5DBE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-28 00:12 UTC, auanasgheps commented
Sure, great!

Hopefully you added more/different sentences than me, to make the detection much better.

I was also missing some files in the test folder, I won't do the job twice and will wait for your PR. You can directly PR my repository, and will land here.

2022-12-28 00:37 UTC, xraver commented
Ok.
I'll do tomorrow!
I will fork your repos and then merge with it.

Il Mar 27 Dic 2022, 19:13 Oliver Cervera ***@***.***> ha
scritto:

> Sure, great!
>
> Hopefully you added more/different sentences than me, to make the
> detection much better.
>
> I was also missing some files in the test folder, I won't do the job twice
> and will wait for your PR. You can directly PR my repository, and will land
> here.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/home-assistant/intents/pull/157#issuecomment-1366273436>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALJM7AZOG4RA5XRRVUX3BFDWPOAZJANCNFSM6AAAAAATKL5DBE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-28 20:41 UTC, balloob commented
Please make sure to run the validate and test commands locally. That way it’s faster to find issues.

Our recommendation for new languages is to only translate the errors in `_common.yaml` and the files starting with `homeassistant_`. Big PRs can get stuck on missing tests for a file that could also be added later.

2022-12-28 23:04 UTC, alessandroias requested changes
Thank you very much for carrying on this translation.
Very willing to help. Here a couple of oversights I found with a quick read.

2022-12-28 23:04 UTC, alessandroias commented on tests/it/climate_HassClimateGetTemperature.yaml
> +      - "Che temperatura c'è"
```suggestion
      - "Che temperatura c'è?"
```

2022-12-29 00:15 UTC, xraver commented
I put my work in @auanasgheps patch.
@alessandroias if you want to contribuite I suggest you to wait the merge between @auanasgheps and mine and then you can revise it.
Is it fine for you?
@balloob yes thanks. Starting from the great work of @auanasgheps before sending the merge request I've tested all sentences as described in the manual usin pytest. This is very helpful!

best regards.

2022-12-29 00:30 UTC, auanasgheps commented
Here we go, I merged the great work from @xraver who added a lot of intents and fixed some typos.

2022-12-29 00:36 UTC, auanasgheps commented
There are a couple of stupid conflicts that I can't resolve, but the rest is looking good.

2022-12-29 00:36 UTC, xraver commented
Thanks!
now we have all CI test passed!

2022-12-29 00:51 UTC, xraver commented
> There are a couple of stupid conflicts that I can't resolve, but the rest is looking good.

where do you find them? i can try to fix

2022-12-29 01:46 UTC, xraver commented
CLI notifies issue

Language: it
 - sentences/it/climate_HassClimateGetTemperature.yaml: invalid format: Sentences should only contain words and matching syntax. They should not contain punctuation. @ data['intents']['HassClimateGetTemperature']['data'][0]['sentences'][1]. Got "[(<what_is> | che)] <temp> [c'è]"
Sentences should only contain words and matching syntax. They should not contain punctuation. @ data['intents']['HassClimateGetTemperature']['data'][0]['sentences'][3]. Got "quanto (caldo | freddo) [(è | c'è | fa)] [(<in>|<the>) <area>]"
Sentences should only contain words and matching syntax. They should not contain punctuation. @ data['intents']['HassClimateGetTemperature']['data'][0]['sentences'][4]. Got "quanto [(è | c'è | fa)] (caldo | freddo) [(<in>|<the>) <area>]"
Sentences should only contain words and matching syntax. They should not contain punctuation. @ data['intents']['HassClimateGetTemperature']['data'][0]['sentences'][5]. Got "[(<what_is> | che)] <temp> [c'è] [<in>] <area>"

I think it refers to "c'è" but it's a standard sentence in italy...

2022-12-29 01:51 UTC, synesthesiam commented
The punctuation validation is a bit too aggressive. I'm seeing what I can do :)

2022-12-29 01:57 UTC, xraver commented
> The punctuation validation is a bit too aggressive. I'm seeing what I can do :)

No problem!

I've executed all test before commit and I have no issue.
I've repeated again and no issue...
/script/lint
/script/test
don't know why...

2022-12-29 03:05 UTC, synesthesiam commented
Please rebase on `main` and try again

2022-12-29 17:58 UTC, xraver commented
Ok all test passed!

2022-12-29 18:02 UTC, merged

2022-12-29 18:04 UTC, xraver commented
Thanks!!!