Norwegian translation of sensor_HassGetState.yaml
home-assistant/intents pull request #1638
Opened 2023-11-13 22:07 UTC by phellarv

I have tried to translate sentences/en/sensor_HassGetState.yaml and tests/en/sensor_HassGetState.yaml to Norwegian. Constructive criticism is very much appreciated

2023-11-14 13:40 UTC, LaStrada commented
Thanks for the PR! The PR is _huge_ so it will take some time to go through all changes. Also, go through the errors the linter complained about.

2023-11-14 13:41 UTC, LaStrada commented on tests/nb/sensor_HassGetState.yaml
> +language: no
```suggestion
language: nb
```

2023-12-04 20:57 UTC, LaStrada requested changes
Still a few things more that needs to be done. E.g. missing expansion rule:
```
FAILED tests/test_language_sentences.py::test_sensor_HassGetState[nb] - hassil.recognize.MissingRuleError: Missing expansion rule <what_is_the_class_of_name>
```

2023-12-04 20:57 UTC, LaStrada commented on sentences/nb/sensor_HassGetState.yaml
> +          class: "[Total] [mengde av] [forbrukt] vann|[totalt] vannforbruk)"
I belive this one should be like this:
```suggestion
          class: "[Total] ([mengde av] [forbrukt] vann|[totalt] vannforbruk)"
```

2023-12-11 21:58 UTC, tetele commented
@phellarv please mark your PR as ready for review if it's ready

2023-12-11 22:06 UTC, phellarv commented
Sorry - Sick at the moment - Will work some more on it as soon as I get well.

2023-12-29 23:25 UTC, andebor commented
@phellarv I took the liberty of drafting an initial version of the Norwegian translation of the `what_is_the_class_of_name` missing from your PR in https://github.com/home-assistant/intents/pull/1837. This PR also shows you how the fixtures relates to the test cases.

2024-01-04 10:49 UTC, phellarv commented
> @phellarv I took the liberty of drafting an initial version of the Norwegian translation of the `what_is_the_class_of_name` missing from your PR in #1837. This PR also shows you how the fixtures relates to the test cases.

Excellent - I will pick up working on this as soon as my son leaves for University tuesday the coming week, and I will get back my PC. :-)

2024-01-20 14:44 UTC, closed without merging