[DE] person_HassGetState
home-assistant/intents pull request #1657
Opened 2023-11-19 16:15 UTC by steffenrapp

2023-12-09 14:39 UTC, mib1185 requested changes
Hi @steffenrapp 
as always, thanks for contribution 👍 
I think we should adopt the Dutch approach here

2023-12-09 14:39 UTC, mib1185 commented on responses/de/HassGetState.yaml
> +        {% endif %}
```suggestion
      wo: |
         {% if state.state == "not_home" %} 
           {{ slots.name | capitalize }} ist weg
         {% elif state.state == "home" %} 
           {{ slots.name | capitalize }} ist zuhause 
         {% else %} 
           {{ slots.name | capitalize }} ist im Bereich {{ state.state }} 
         {% endif %} 
```

i think the Dutch approach fits better in this case
https://github.com/home-assistant/intents/blob/09ad6c6abbc04671d776bd8e44f1bf5b3eed3280/responses/nl/HassGetState.yaml#L83-L90

2023-12-10 00:19 UTC, mib1185 requested changes

2023-12-10 00:19 UTC, mib1185 commented on tests/de/person_HassGetState.yaml
> +    response: "Martin ist hier: zuhause"
```suggestion
    response: "Martin ist zuhause"
```

2023-12-10 00:19 UTC, mib1185 commented on tests/de/person_HassGetState.yaml
> +    response: "Lisa ist hier: Arbeit"
```suggestion
    response: "Lisa ist im Bereich Arbeit"
```

2023-12-10 00:25 UTC, mib1185 commented on responses/de/HassGetState.yaml
> +         {% endif %}
```suggestion
      wo: |
        {% if state.state == "not_home" %}
          {{ slots.name | capitalize }} ist weg
        {% elif state.state == "home" %}
          {{ slots.name | capitalize }} ist zuhause
        {% else %}
          {{ slots.name | capitalize }} ist im Bereich {{ state.state }}
        {% endif %}
```

2023-12-10 00:27 UTC, mib1185 approved these changes

2023-12-10 00:38 UTC, mib1185 commented on tests/de/_fixtures.yaml
> +    state: "zuhause"
```suggestion
    state: "home"
```

2023-12-10 09:51 UTC, steffenrapp commented
@mib1185 thanks for the review and the contributions. I'm working on fixing the errors. Have to rebuild some of the logic.

2023-12-10 11:12 UTC, steffenrapp commented
@mib1185 I adapted the logic and added more tests. Hope it's fine, maybe I can do a little bit more refinement in a separate PR afterwards. Also I want to use the new expansion rule <wieviel> everywhere else where it fits.

2023-12-10 12:42 UTC, mib1185 requested changes
Hi @steffenrapp there are some comments from my side, thx 👍

2023-12-10 12:42 UTC, mib1185 commented on sentences/de/person_HassGetState.yaml
> +          domain: person
i think we do not need to set the `domain` here, because above we already require the domain to be `person` 🤔

2023-12-10 12:42 UTC, mib1185 commented on sentences/de/person_HassGetState.yaml
> +          - "<wieviel> (Personen|Menschen) <befinden> <zuhause>"
i think we can make `(Personen|Menschen)` an expansion rule and add `Leute` to possible values 🙂

2023-12-10 12:42 UTC, mib1185 commented on responses/de/HassGetState.yaml
> +      einzeln_zone: |
i think this is to complex and may lead to confusing replies like:
question: Ist Jonas auf Arbeit?
answer: Nein, ist nicht zu Hause

so we should just reply with ja/nein. if the user want's to know, where a person is, the user can ask for it ^^

2023-12-10 13:11 UTC, mib1185 commented on sentences/de/person_HassGetState.yaml
> +          domain: person
this should also count for the sentences below 😉

2023-12-12 20:57 UTC, mib1185 commented on sentences/de/person_HassGetState.yaml
> +          domain: person
after some testing it figured out, that setting `slot.domain` is still needed, even we already require domain to be person 🤔

2023-12-12 21:17 UTC, mib1185 commented
Hi @steffenrapp 
based on https://github.com/home-assistant/intents/discussions/1768#discussioncomment-7835392 this branch has been rebased on [untranslated-state](https://github.com/home-assistant/intents/tree/untranslated-state) and is going to be merged there.

2023-12-12 21:17 UTC, mib1185 approved these changes

2023-12-12 21:19 UTC, merged