[de] Add area slots for scenes
home-assistant/intents pull request #1830
Opened 2023-12-25 14:24 UTC by andreasbrett

allow activation of area-specific scenes by adding area slots (see https://github.com/home-assistant/intents/issues/1788)

2023-12-27 15:13 UTC, mib1185 requested changes
Hi @andreasbrett 

thanks for this contribution 👍 
There are only some small comments from my side.

2023-12-27 15:13 UTC, mib1185 commented on tests/de/scene_HassTurnOn.yaml
> +		domain: scene
```suggestion
        domain: scene
```

2023-12-27 15:13 UTC, mib1185 commented on sentences/de/scene_HassTurnOn.yaml
> +        response: scene
there are missing blank lines at the end of the files

2023-12-28 13:18 UTC, andreasbrett commented
Hi @mib1185,
thanks for the comments, fixed both issues.

2023-12-28 17:59 UTC, mib1185 commented
Hi @andreasbrett 
I guess this PR should be **Ready for review** now (_short hint about https://github.com/home-assistant/intents/pull/1830#issuecomment-1870395280_)?

2023-12-28 18:00 UTC, mib1185 approved these changes

2024-01-01 22:05 UTC, merged