vacuum intents creation
home-assistant/intents pull request #2072
Opened 2024-03-10 23:00 UTC by dziadeck47

Added vaccuum intents and excluded vacuum domain from generic hassturnon (as it was catching the vacuum turn on incorrectly)

2024-03-11 10:23 UTC, tetele requested changes

2024-03-11 10:23 UTC, tetele commented on sentences/en/vacuum_HassVacuumReturnToBase.yaml
> +language: pl
Modified the wrong file here

2024-03-11 10:27 UTC, Uriziel01 commented
@dziadeck47 This PR is duplicating most of the changes from https://github.com/home-assistant/intents/pull/1996/files isn't it?

2024-06-08 15:13 UTC, frenck commented
Since there was no response at all, I'm declaring this PR stale and closing it.
Feel free to re-open this PR when you feel like that is the appropriate thing to do.

../Frenck

2024-06-08 15:13 UTC, closed without merging