[EN] Improvement on how we turn on and off lights in a room and in the whole house.
home-assistant/intents pull request #2100
Opened 2024-03-21 14:25 UTC by jlpouffier

I took the liberty to improve the English language based on what has been done in French.

The general gist of is that I defined expansion rules for `<all>`, `<everywhere>` and `<here>`

Then I applied the following logic (Illustrated with `TurnOff` but similar for `TurnOn`)

**Targets the current room**:
- Turn on lights
- Turn on lights `<here>`
- Turn on `<all>` lights `<here>`

**Targets the whole house**:
- Turn on `<all>` lights
- Turn on lights `<everywhere>`
- Turn on `<all>` lights `<everywhere>`

Work done
- LightTurnOn
- LightTurnOff
- Tests

2024-03-21 14:36 UTC, tetele reviewed
Some things could be contracted, but it's probably more readable this way. Let me know what you want to do

2024-03-21 14:47 UTC, synesthesiam requested changes

2024-03-21 14:47 UTC, synesthesiam commented on tests/en/light_HassTurnOn.yaml
> +      - Switch on every lights in the home
```suggestion
      - Switch on every light in the home
```

English speakers wouldn't use the plural "lights" in this or some of the other sentences.

2024-03-21 14:47 UTC, synesthesiam commented on tests/en/light_HassTurnOn.yaml
> +      - Activate each and every lights everywhere
```suggestion
      - Activate each and every light everywhere
```

2024-03-21 14:47 UTC, synesthesiam commented on tests/en/light_HassTurnOn.yaml
> +      - Turn on every lights
```suggestion
      - Turn on every light
```

2024-03-21 14:47 UTC, synesthesiam commented on tests/en/light_HassTurnOff.yaml
> +      - Turn every lights off in this room
```suggestion
      - Turn every light off in this room
```

2024-03-21 14:47 UTC, synesthesiam commented on tests/en/light_HassTurnOff.yaml
> +      - Turn every lights in here off
```suggestion
      - Turn every light in here off
```

2024-03-21 14:47 UTC, synesthesiam commented on tests/en/light_HassTurnOff.yaml
> +      - Switch off each and every lights in the room
```suggestion
      - Switch off each and every light in the room
```

2024-03-21 14:47 UTC, synesthesiam commented on tests/en/light_HassTurnOn.yaml
> +      - Activate every single lights
```suggestion
      - Activate every single light
```

2024-03-21 14:47 UTC, synesthesiam commented on tests/en/light_HassTurnOn.yaml
> +      - Turn every lights on in this room
```suggestion
      - Turn every light on in this room
```

2024-03-21 14:47 UTC, synesthesiam commented on tests/en/light_HassTurnOn.yaml
> +      - Turn every lights in here on
```suggestion
      - Turn every light in here on
```

2024-03-21 14:47 UTC, synesthesiam commented on tests/en/light_HassTurnOn.yaml
> +      - Switch on each and every lights in the room
```suggestion
      - Switch on each and every light in the room
```

2024-03-21 14:47 UTC, synesthesiam commented on sentences/en/_common.yaml
> +  all: "(all|all of|every|every single|each|each and every)"
I think it's a bit more readable to leave out the optionals here, though I agree it's more compact.

2024-03-21 14:47 UTC, synesthesiam commented on sentences/en/_common.yaml
> +  here: "(here|in here|in this room|in the room)"
Same as above comment. While less compact, I think the version from @jlpouffier is more readable.

2024-03-21 14:54 UTC, jlpouffier commented on sentences/en/_common.yaml
> +  all: "(all|all of|every|every single|each|each and every)"
Honestly: Up to you two.
I know that personally in French we decided to fight against any kind of complexity that would prevent someone from contributing, even if it means duplicating a few things.

But here I am just a contributor, I do not maintain these sentences.

So tell me I'll do it ;)

2024-03-21 15:39 UTC, tetele commented
I'm on vacation this week, i'd probably be late to reply and don't want to hold things up, so i'll let @synesthesiam decide.

2024-03-21 15:40 UTC, synesthesiam commented on sentences/en/_common.yaml
> +  everywhere: "(everywhere|in all [the] rooms|in every room[s]|in each room|in the <home>)"
Technically, having `all [the] rooms` will result in a double space in the output when "the" is left out: `all  rooms`. I have to have special logic to deal with this elsewhere during matching.

Adding the whitespace to the optional makes it produce the correct output with a single space.

2024-03-21 15:41 UTC, tetele commented on sentences/en/_common.yaml
> +  everywhere: "(everywhere|in all [the] rooms|in every room[s]|in each room|in the <home>)"
For super efficiency. When `the` is missing, contracting 2 pieces of whitespace (before and after `the`) into 1 when matching takes up a tiny bit more computing cycles.

2024-03-21 15:42 UTC, synesthesiam requested changes

2024-03-21 15:42 UTC, synesthesiam commented on tests/en/light_HassTurnOff.yaml
> +      - Switch off every lights in the home
```suggestion
      - Switch off every light in the home
```

2024-03-21 15:42 UTC, synesthesiam commented on tests/en/light_HassTurnOff.yaml
> +      - Turn off every lights
```suggestion
      - Turn off every light
```

2024-03-21 15:42 UTC, synesthesiam commented on tests/en/light_HassTurnOff.yaml
> +      - Deactivate every single lights
```suggestion
      - Deactivate every single light
```

2024-03-21 16:13 UTC, jlpouffier commented on sentences/en/_common.yaml
> +  everywhere: "(everywhere|in all [the] rooms|in every room[s]|in each room|in the <home>)"
Huh? We have this like everywhere in every language :D Weird!

2024-03-27 14:40 UTC, synesthesiam approved these changes

2024-03-27 14:40 UTC, merged