Update _common.yaml
home-assistant/intents pull request #2125
Opened 2024-04-06 22:38 UTC by omaramin-2000

Improve the Arabic language responses

2024-04-15 17:50 UTC, Natfaji requested changes

2024-04-15 17:50 UTC, Natfaji commented on sentences/ar/_common.yaml
> +  turn: "(غير|اضبط||أضبط||إضبط|ضبط)"
double pipes "||" are unnecessary.

2024-04-15 17:50 UTC, Natfaji commented on sentences/ar/_common.yaml
> +  turn_on: "(افتح|شغل|اشعل|أشعل|اشغل||أشغل|ابدأ||إبدأ|شعل|فعل|تفعيل|تشغيل|فعل)"
double pipes "||" are unnecessary.

2024-04-15 17:50 UTC, Natfaji commented on sentences/ar/_common.yaml
> +  turn_off: "(أغلق|اغلق|اطفئ||أطفئ|طفي)"
double pipes "||" are unnecessary.

2024-04-15 22:26 UTC, omaramin-2000 commented
Alright, I need help with the modifications cause the test fails, can you tell me what else I need to modify?

2024-04-18 19:24 UTC, Natfaji requested changes

2024-04-18 19:24 UTC, Natfaji commented on tests/ar/light_HassLightSet.yaml
>        - "اضبط لون ضوء المطبخ الرئيسي الى احمر"
the problem is that the word "احمر" is misspelled, it should be "أحمر". this also applies for all other "احمر" is this file

2024-04-18 19:24 UTC, Natfaji commented on tests/ar/light_HassLightSet.yaml
>        - "اضبط لون جميع الاضواء الى احمر"
same

2024-04-18 19:24 UTC, Natfaji commented on tests/ar/light_HassLightSet.yaml
>        - "اضبط لون جميع الاضواء الى احمر في المطبخ"
same

2024-04-18 21:42 UTC, Natfaji requested changes
add both way to say red ("أحمر" and "احمر") to each response

2024-04-18 21:51 UTC, Natfaji approved these changes

2024-04-18 21:56 UTC, Ahmed-farag36 approved these changes

2024-04-18 21:58 UTC, Natfaji commented on sentences/ar/_common.yaml
> +  turn: "(غير|اضبط||أضبط|إضبط|ضبط)"
missed that one

2024-04-19 03:22 UTC, Ahmed-farag36 approved these changes

2024-04-22 12:11 UTC, merged