Issue 2148 correction
home-assistant/intents pull request #2165
Opened 2024-05-07 16:16 UTC by Jeffx59

2024-05-07 20:42 UTC, jlpouffier requested changes

2024-05-07 20:42 UTC, jlpouffier commented on sentences/fr/_common.yaml
> +  met_mets_mettre_dirty: "(mais|maître)"
just call it `mets_dirty` ;)

2024-05-08 11:10 UTC, piitaya approved these changes

2024-05-08 16:25 UTC, piitaya approved these changes

2024-05-08 17:43 UTC, Jeffx59 reviewed
Done

2024-05-09 12:31 UTC, jlpouffier approved these changes

2024-05-09 12:32 UTC, merged