[NL] Improvements media_player intents
home-assistant/intents pull request #2479
Opened 2024-11-07 15:39 UTC by TheFes

* Make all media_player intents area aware
* add area support to all media_player intents
* add additional options to `<media_item>` expansion rule

Other change
* Add `wil je` to `skip_words`. This will allow sentences like `wil je het volgende liedje opzetten`. I've noticed my kids tend to include `wil je` when they try to ask something.

2024-11-08 07:46 UTC, frenck requested changes

2024-11-08 07:46 UTC, frenck commented on sentences/nl/media_player_HassMediaUnpause.yaml
> +          - "ga verder met [de |het]<media_item>"
```suggestion
          - "ga verder met [de |het ]<media_item>"
```

2024-11-08 07:46 UTC, frenck commented on sentences/nl/media_player_HassMediaUnpause.yaml
> +          - "ga verder met [de |het]<media_item> <in> <area>"
```suggestion
          - "ga verder met [de |het ]<media_item> <in> <area>"
```

2024-11-08 08:23 UTC, TheFes commented
Removed all spaces in optional parts.
Also added optional `<media_type>` mention to pause sentences (was already added to unmpause)

2024-11-09 15:15 UTC, frenck approved these changes
Thanks, @TheFes 👍 

../Frenck

2024-11-09 15:15 UTC, merged