[FI] Areas rework part 1 of many
home-assistant/intents pull request #2501
Opened 2024-11-11 15:39 UTC by salleq

- Added conjugations for areas

- simplified home_assistant_HassTurnOn 

- made some other changes to common and fixtures

2024-11-17 16:43 UTC, Arkkimaagi commented
I've been thinking this approach. I think it's quite problematic and we need to consider it more.

You've added support for two special rooms, ullakko and eteinen, but what if the people have "kura-eteinen" or something similar? I mean, we really can not anticipate all the rooms and names people give to their areas.

2024-11-17 17:30 UTC, v1k70rk4 commented
Hi, since we’re part of the same language family, I ran a test, and as I see, it works in Finnish too :) 

In Hungarian, there are some words where the root changes, so I added "filler words" after the area. For example: room, space, and it works.

So, for cases where the word cannot be conjugated, you can still use these. In your case, it might look something like this: Sytytä ullakko huoneen lamppu. Of course, words that can be conjugated without altering the root can still be supported.

This is precisely why I suggested creating a guide in everyone’s native language to explain usage. But until we can modify word roots, I’ve been solving it in Hungarian in this way.

Consider whether this works in all special cases.

2024-11-17 18:04 UTC, Arkkimaagi commented
Yep, that's the option salleq is changing with this pr away from.

And the words fo not behave nicely, for eteinen, the extra word does not work as well.

It's also kinda difficult to remember what filler words to add.

2024-11-18 09:22 UTC, salleq commented
This PR _adds_ the option for conjugated room names, I'm _not_ taking away the possibility to say "laita huoneen olohuone valo päälle" ("put the light on in the room living room"). You can see that I have added some tests, but not removed any.

We can't possibly take into account every room name there is (like "kura-eteinen") and what people will use, but the most common ones we can + some rooms that aren't conjugated nicely (ullakko and eteinen for example). 

I don't see how this could be better implemented unless we get Arkkimaagi's lemmatization idea go through or something similar.

It's more for us to maintain (having both conjugations and area {area} ) but I can't agree on talking to the voice assistant using filler words, it's not natural.

2024-11-22 10:03 UTC, Arkkimaagi requested changes
All in all, I love how you've taken care of this project on the Finnish translations. Since we've been discussing in discord and you asked for my opinion, I've checked the code. We can discuss further.

2024-11-22 11:35 UTC, salleq commented on sentences/fi/_common.yaml
> +  eteinen_pääte: "(eteinen|eteisessä|eteisestä|eteiseen|eteiselle|eteiseltä|eteisen)"
Just tested this - Had a light in a room called "Ullakko", and asked HA to "Sammuta ullakon valo". So it works.

2024-11-22 15:05 UTC, salleq commented on sentences/fi/_common.yaml
> +  alue_pääte: "({area}[e][ssa|ssä|sta|stä|än|in|an|on|ön|seen|ltä|llä|lla|lta|lle|n])"
as discussed, this probably won't matter even though the variants are multiplied. But - can be tested if necessary.

2024-11-22 18:23 UTC, salleq commented on sentences/fi/_common.yaml
> +  alue: "(alue|paikka|huone|tila|<alueen>|<alueessa>|<alueesta>|<alueeseen>|<alueella>|<alueelta>|<alueelle>)" # nominatiivi = mikä, kuka
"alue" is now the base and "alue_taivutus" includes all the conjugations.

2024-11-22 18:25 UTC, salleq commented on sentences/fi/fan_HassTurnOff.yaml
> +          - "<pysäytä> (<tuuletin>;(<huone>|<alue> <huone>|<alue_pääte>))"
discussed quite a bit about all these issues today in discord. if something doesn't seem how we agreed, please let me know.

2024-11-22 19:19 UTC, salleq commented
There's more to be done obviously but I think I should freeze this PR with these changes unless there's something really out of place. 

I'll clean out the commented out stuff that's to be deleted, before merging this.

2024-11-26 19:33 UTC, Arkkimaagi approved these changes

2024-11-26 19:38 UTC, merged