added timer Start/Cancel/Status and AddItem
home-assistant/intents pull request #2568
Opened 2024-11-18 07:47 UTC by nic0dk

[DA] _common.yaml 
- added wildcard for shopping_list_item
- timer seconds/minutes/hours/half/quarter
- expansion rules timer pause/add/decrease/set/cancel/duration/start

[DA] homeassistant_HassStartTimer.yaml
[DA] todo_HassListAddItem.yaml
[DA] homeassistant_HassCancelTimer.yaml
[DA] homeassistant_HassTimerStatus.yaml
[DA] homeassistant_HassNevermind.yaml

2024-11-18 12:24 UTC, MTrab approved these changes
Looks good to me

2024-11-18 12:29 UTC, MTrab requested changes
Tests are missing for these files

2024-11-19 08:30 UTC, MTrab requested changes
Typos?

2024-11-19 08:30 UTC, MTrab commented on tests/da/homeassistant_HassCancelTimer.yaml
> +    response: Nedtælling afbrydt
Typo, I guess

2024-11-19 08:30 UTC, MTrab commented on tests/da/homeassistant_HassCancelTimer.yaml
> +    response: Nedtælling afbrydt
Another

2024-11-19 08:30 UTC, MTrab commented on tests/da/homeassistant_HassCancelTimer.yaml
> +    response: Nedtælling afbrydt
Again

2024-11-19 08:30 UTC, MTrab commented on tests/da/homeassistant_HassCancelTimer.yaml
> +    response: Nedtælling afbrydt
One more

2024-11-19 08:34 UTC, MTrab commented on tests/da/todo_HassListAddItem.yaml
> +      - tilføj æbler til i dagligvarer
Shouldn't that be `tilføj æbler til dagligvarer` ?

2024-11-19 09:26 UTC, nic0dk commented
@MTrab hope we nailed all the typo's, else let me know

2024-11-19 09:28 UTC, MTrab approved these changes

2024-11-19 09:29 UTC, merged