Update light_HassLightSet.yaml
home-assistant/intents pull request #263
Opened 2023-01-04 23:39 UTC by vladacr

Přidány základní věty pro jas a barvu

2023-01-05 20:43 UTC, halecivo requested changes

2023-01-05 20:43 UTC, halecivo commented on sentences/cs/light_HassLightSet.yaml
> +      #jas | brightness
Maybe I'm having my OCD moment here, but would be happier if there was a space between # and jas in the same way as you did for # barva | color.

2023-01-06 11:24 UTC, TomaszPilch commented
You are missing tests in `tests` folder

2023-01-08 09:33 UTC, halecivo commented
closing due to inactivity - work already done in different PR

2023-01-08 09:33 UTC, closed without merging