Adding initial Hebrew support for sentences.
home-assistant/intents pull request #32
Opened 2022-12-20 09:35 UTC by haim-b

2022-12-21 06:14 UTC, yuvalabou commented on sentences/he/homeassistant_HassTurnOn.yaml
> +          - "להדליק [את] [ה]<name>"
```suggestion
          - "להדליק [את] [ה]<name>"
          - "הפעל [את] [ה]<name>"
          - "הפעלה [של] [ה]<name>"
          - "תפעיל [את] [ה]<name>"
```

2022-12-23 21:44 UTC, synesthesiam commented
@haim-b Can you please remove the "HassToggle" intent? We decided it wasn't worth including for now.

2022-12-24 17:45 UTC, yuvalabou commented on README.md
> +| `he` | Hebrew           | @haim-b, @leranp   |
```suggestion
| `he` | Hebrew           | @haim-b, @leranp, @yuvalabou    |
```

2022-12-25 09:36 UTC, thecode requested changes
codeowners should be on the same line and it is better to do them in order of adding (reduce line changes_

2022-12-25 09:36 UTC, thecode commented on CODEOWNERS
>  tests/he/ @leranp
```suggestion
sentences/he/ @leranp @haim-b
responses/he/ @leranp @haim-b
tests/he/ @leranp @haim-b
```

2022-12-25 09:36 UTC, thecode commented on README.md
> +| `he` | Hebrew           | @haim-b, @leranp   |
```suggestion
| `he` | Hebrew           | @leranp, @haim-b |
```

2022-12-25 11:18 UTC, thecode approved these changes
Merging this into a branch so others can help with the tests

2022-12-25 11:18 UTC, merged