Update homeassistant_HassTurnOn.yaml
home-assistant/intents pull request #338
Opened 2023-01-05 16:05 UTC by VladimirV01

Added some more options for this action

2023-01-11 22:25 UTC, tetele commented
Lipsesc testele pentru propozitie.

Verbul "a comuta" la imperativ singural e "comută", nu "comutează".

De asemenea, ar fi bine sa adaugi variantele cu/fara diacritice pentru propozitia/particula de interpretat (i.e. `comut(ă|a)`, `porne(ș|s)te`).

2023-01-11 22:26 UTC, tetele requested changes
Lipsesc testele pentru propozitie.

Verbul "a comuta" la imperativ singural e "comută", nu "comutează".

De asemenea, ar fi bine sa adaugi variantele cu/fara diacritice pentru propozitia/particula de interpretat (i.e. `comut(ă|a)`, `porne(ș|s)te`).

2023-01-12 06:17 UTC, VladimirV01 commented
> Lipsesc testele pentru propozitie.
> 
> Verbul "a comuta" la imperativ singural e "comută", nu "comutează".
> 
> De asemenea, ar fi bine sa adaugi variantele cu/fara diacritice pentru propozitia/particula de interpretat (i.e. `comut(ă|a)`, `porne(ș|s)te`).

@tetele multumesc pentru sugestii. 
Daca inteleg corect trebuie mai intai de facut commit la teste si apoi la propozitii?

2023-01-12 06:38 UTC, closed without merging

2023-01-12 06:55 UTC, tetele commented
@VladimirV01 nu conteaza ordinea in care faci commit, important e sa fie in acelasi pull request noile propozitii si testele pentru ele.

2023-01-12 06:58 UTC, VladimirV01 commented
Understood! Thanks. :)