[DE] Added cover and a few other sentences
home-assistant/intents pull request #42
Opened 2022-12-20 21:55 UTC by IceBeach7

2022-12-20 22:29 UTC, ThomDietrich commented on sentences/de/_common.yaml
> +  cover_variants: "(das tor | (die | alle) tore | das rollo | (die | alle) rollos | die abdeckung | (die | alle) abdeckungen)"
Imho nicht vollständig und Substantive sollten großgeschrieben sein

2022-12-22 04:32 UTC, synesthesiam commented
@Scorpoon can you take a look at these changes please?

2022-12-22 08:49 UTC, kroimon requested changes

2022-12-22 08:49 UTC, kroimon commented on sentences/de/_common.yaml
> +  cover_variants: "(das Tor | (die | alle) Tore | die Garage | (die | alle) Garagen | das Garagentor | (die | alle) Garagentore | das Rollo | (die | alle) Rollos | die Abdeckung | (die | alle) Abdeck
I would also add "Rollladen" (roller shutter) here as this is probably a very common cover to control.

2022-12-22 08:49 UTC, kroimon commented on sentences/de/cover_HassCloseCover.yaml
> +          - "schließe <cover_variants> <area>"
If you are adding the "(mach | mache) ... <turn_on/turn_off>" variants to other domains, I suggest also adding this to the covers, e.g. "mache die Garage zu".
Even if "mache <something>" is not the highest form of German, I guess it it used quite often.

2022-12-22 08:49 UTC, kroimon commented on sentences/de/fan_HassTurnOff.yaml
> +          - "(mach | mache) <area> (den Ventilator | (die | alle) Ventilatoren) [<turn_off>]"
Similar to the existing sentences above:
```suggestion
          - "(mach | mache) <area> (den Ventilator | (die | alle) Ventilatoren) [<turn_off>]"
          - "(mach | mache) (den Ventilator | (die | alle) Ventilatoren) <area> [<turn_off>]"
```

2022-12-22 08:49 UTC, kroimon commented on sentences/de/fan_HassTurnOn.yaml
> +          - "(mach | mache) <area> (den Ventilator | (die | alle) Ventilatoren) [<turn_on>]"
Similar to the existing sentences above:
```suggestion
          - "(mach | mache) <area> (den Ventilator | (die | alle) Ventilatoren) [<turn_on>]"
          - "(mach | mache) (den Ventilator | (die | alle) Ventilatoren) <area> [<turn_on>]"
```

2022-12-22 08:49 UTC, kroimon commented on sentences/de/light_HassTurnOff.yaml
> +          - "(mach | mache) <area> (das Licht | (die | alle) Lichter) <turn_off>"
Similar to the existing sentences above:
```suggestion
          - "(mach | mache) <area> (das Licht | (die | alle) Lichter) <turn_off>"
          - "(mach | mache) (das Licht | (die | alle) Lichter) <area> <turn_off>"
```

2022-12-22 08:49 UTC, kroimon commented on sentences/de/light_HassTurnOn.yaml
> +          - "(mach | mache) <area> (das Licht | (die | alle) Lichter) <turn_on>"
Similar to the existing sentences above:
```suggestion
          - "(mach | mache) <area> (das Licht | (die | alle) Lichter) <turn_on>"
          - "(mach | mache) (das Licht | (die | alle) Lichter) <area> <turn_on>"
```

2022-12-22 08:49 UTC, kroimon commented on sentences/de/cover_HassOpenCover.yaml
> +          - "öffne <area> <cover_variants>"
This is a duplicate and should probably be:
```suggestion
          - "öffne <area> <cover_variants>"
          - "öffne <cover_variants> <area>"
```

2022-12-23 13:10 UTC, mib1185 requested changes
Hi @IceBeach7 

thanks for this contribution 👍 

You need to rebase your branch to the latest `main` so you will get the newest expansion rules. With these you can adjust the `homeassistant` and `light` sentences. The `cover` and `fan` sentences were meanwhile added by #92, so you can skip them in this PR.

regards,
Michael

2022-12-23 13:16 UTC, kroimon commented
I think this is now obsolete as it was basically the base for #92

2022-12-23 13:23 UTC, mib1185 commented
there are still open additions to the `homeassistant` and `light` sentences, which were not covered by #92 (_or any later PR_)

2023-01-08 01:54 UTC, balloob commented
This PR has gone stale. Please open a new PR without conflicts if you want to incorporate these changes.

2023-01-08 01:54 UTC, closed without merging