[BG] optimisation to code
home-assistant/intents pull request #651
Opened 2023-01-14 14:15 UTC by BossNeo

1. Merge C and F in short format
2. Took out < lampi_brightness > words forbrightness for more clean view of code
3. Add more native words to set up lights
4. Adding sentece to test the new words

2023-01-16 01:58 UTC, hristo-atanasov requested changes
Освен другите коментари, които съм ти написал, можеш да смениш  на всички места `lampi` с `lights` ..

2023-01-16 01:58 UTC, hristo-atanasov commented on sentences/bg/_common.yaml
> +  set: (направи | сложи | постави | смени | промени | настрой | задай | нагласи | тури | увеличи | намали )
`увеличи` и `намали` не са подходящ превод за `set`

2023-01-16 23:13 UTC, BossNeo commented on sentences/bg/_common.yaml
> +  set: (направи | сложи | постави | смени | промени | настрой | задай | нагласи | тури | увеличи | намали )
Ok agree Tommorow will fax all that and will add set max functionality. Sorry for the delay

2023-01-23 21:19 UTC, hristo-atanasov commented
You should fix the conflicts.

2023-01-23 21:57 UTC, BossNeo commented
> Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests. 
The button is not active and the conflict acure from MAIN file . I dont know who touch it and left it with error. For that my branch now is not working. There is no problem with this branch at all . 
sentences/bg/cover_HassCloseCover.yaml
sentences/bg/cover_HassOpenCover.yaml
must to be deleted, but that dont solve the problem from main. 
Fix main and delete this request i will make new if need.

2023-01-26 19:53 UTC, BossNeo commented
i create new PR with all fix

2023-01-26 19:53 UTC, closed without merging