Update climate_HassClimateGetTemperature.yaml
home-assistant/intents pull request #833
Opened 2023-02-01 07:49 UTC by OliverSkivdal

2023-02-06 17:36 UTC, synesthesiam commented
@LaStrada please coordinate with @OliverSkivdal to see if this PR is still needed

2023-02-07 03:43 UTC, LaStrada requested changes
Added a comment. And also the merge conflict is needed to be addressed.

2023-02-07 03:43 UTC, LaStrada commented on sentences/nb/climate_HassClimateGetTemperature.yaml
> +         - "er det (kaldt | varmt | kjølig) inne"
This line is the only one we need now. You can use `<kaldt_varmt>`, but it need to be updated to include `kjølig` as well.
```suggestion
         - "er det <kaldt_varmt> inne"
```

2023-02-28 09:14 UTC, LaStrada commented
This PR is very outdated, and there has been major changes since this was opened.

2023-02-28 09:14 UTC, closed without merging