Update climate_HassClimateSetTemperature.yaml
home-assistant/intents pull request #835
Opened 2023-02-01 07:51 UTC by OliverSkivdal

2023-02-06 17:36 UTC, synesthesiam commented
@LaStrada

2023-02-07 03:34 UTC, LaStrada commented on sentences/nb/climate_HassClimateSetTemperature.yaml
> +         - "(varm opp | kjøl ned) <area> til <temperature>"
This line still need to be fixed.
```suggestion
         - "(varm opp|kjøl ned) <område> til <temperature>"
```

2023-02-07 03:38 UTC, LaStrada requested changes
This PR need to resolve some conflicts and changes requested.

2023-02-07 03:38 UTC, LaStrada commented on sentences/nb/climate_HassClimateSetTemperature.yaml
> +         - "sett temperaturen til <temperature>"
These lines are not needed anymore.

2023-02-28 09:14 UTC, LaStrada commented
This PR is very outdated, and there has been major changes since this was opened.

2023-02-28 09:14 UTC, closed without merging