Update _common.yaml
home-assistant/intents pull request #837
Opened 2023-02-01 07:58 UTC by chuk-a

2023-02-01 14:54 UTC, schizza requested changes
Stick to #830 rules

2023-02-01 14:54 UTC, schizza commented on sentences/mn/_common.yaml
> +      - "бор"
there must be counterparts to stated values:
eg: 
```
lists:
  color:
     values:
        - in: "цагаан"  #color you are using in your language
        - out: "white"  #color name in English
```

2023-02-01 14:54 UTC, schizza commented on sentences/mn/_common.yaml
> +  window: "(window[s] | blind[s] | curtain[s] | shutter[s])"
No spaces between `|` as new big changes will be added #830

2024-06-08 10:40 UTC, closed without merging

2024-06-08 10:40 UTC, frenck commented
Since there was no response at all, I'm declaring this PR stale and closing it.
Feel free to re-open this PR when you feel like that is the appropriate thing to do.

../Frenck