Add polite questions to the NL sentences
home-assistant/intents pull request #931
Opened 2023-02-06 11:20 UTC by TyzzyT

Currently, the possibility to ask something to Assist is limited. While I think it would be nice if you can also ask it in a polite way to do something. i.e. instead of saying: mag de woonkamer lamp aan, you can ask: zal je de woonkamer lamp aan kunnen zetten?

To accomplish this, I added the following words to the <doe> expansion rule: Kan, kun, zal, zou, zetten, doen, veranderen, schakelen.
And then added the <doe> expansion to the end of the <doe> sentences. This way we leave the current phrases as is and add the polite questions to Assist.
There are two downsides to this setup: 
1. We will also include invalid sentences, you can now also say: 'zetten woonkamer lamp aan' or 'schakelen de keuken licht uit'. If we want to avoid this, we would need two different expansion rules: one for the start of the sentence and one for the end of the sentence. Right now I kept using one expansion rule, because it makes things easier.
2. The reading of the code in the intents repo will be harder, because every <doe> sentence will end with another optional <doe>. For anyone who wants to contribute to this repo it can be hard to read.

I understand that this is a big change in how we handle the interactions with Assist, so if you don't like the way I changed it: feel free to start a discussion or discard this PR.

2023-02-06 12:34 UTC, TyzzyT commented
Some tests are failing, but it looks like they fail on other sentences than I added. I'll set this PR to Ready for review and will look at the tests at a later moment. To prevent a lot of work when this PR will not be accepted.

2023-02-06 13:01 UTC, TheFes commented
I see tests are failing, but on older tests. Must be because of an Hasil update.
I'll look into this ASAP

2023-02-06 13:37 UTC, TheFes commented
@synesthesiam there seems to be a bug in the parser now
`"[<doe>] (alle|in) <area>[' ']<lamp> aan [willen | kunnen] [<doe>]"` fails on `'Mogen in de keuken de lampen aan?'`
It does work if I add optional spaces in the newly added part (`[<doe>] (alle|in) <area>[' ']<lamp> aan[ ][willen | kunnen][ ][<doe>]`) so it seems to fail on missing spaces in the sentence.

Without optional spaces:
```
@TheFes ➜ /workspaces/intents (main) $ python3 -m script.intentfest parse --language nl --sentence 'Mogen in de keuken de lampen aan?'
{
  "text": "Mogen in de keuken de lampen aan?",
  "match": false
```

With optional spaces:
```
@TheFes ➜ /workspaces/intents (main) $ python3 -m script.intentfest parse --language nl --sentence 'Mogen in de keuken de lampen aan?'
{
  "text": "Mogen in de keuken de lampen aan?",
  "match": true,
  "intent": "HassTurnOn",
  "slots": {
    "area": "keuken",
    "domain": "light",
    "name": "all"
  },
  ```

2023-02-06 16:02 UTC, TheFes commented
@synesthesiam It also works without the optional spaces if I don't add the question mark at the end.
So `'Mogen in de keuken de lampen aan'`  works. If a add any punctuation mark, it fails.

2023-02-06 17:03 UTC, synesthesiam commented
I applied a fix to hassil. Please update and try again :+1:

2023-02-06 17:23 UTC, TheFes commented
@TyzzyT Well, now it at least only fails on the tests you added 😉

2023-02-07 07:53 UTC, TheFes requested changes

2023-02-07 07:53 UTC, TheFes commented on tests/nl/light_HassLightSet.yaml
> +      - "Zal je de slaapkamerverlichting naar 50% willen doen?"
For this test the brightness is set to 75%, you are using 50% which is causing the test to fail

2023-02-07 07:53 UTC, TheFes commented on tests/nl/light_HassLightSet.yaml
> +      - "Kunt u de slaapkamerlamp blauw doen?"
This test checks for the entity `slaapkamerlamp` which is one word

2023-02-07 07:53 UTC, TheFes commented on tests/nl/light_HassTurnOff.yaml
> +      - "Kunt u de keukenverlichting uit doen?"
turning on/off all lights in an area needs either `alle` or `in` before `<area>` because it otherwise can conflict with toggling an entity.

2023-02-07 07:53 UTC, TheFes commented on tests/nl/homeassistant_HassTurnOn.yaml
> +      - "Zal je de slaapkamer lamp aan willen doen?"
This test checks for the entity `slaapkamerlamp` which is one word

2023-02-07 07:53 UTC, TheFes commented on tests/nl/homeassistant_HassTurnOff.yaml
> +      - "Zal je de slaapkamer lamp uit willen doen?"
This test checks for the entity `slaapkamerlamp` which is one word

2023-02-07 08:02 UTC, TheFes commented
@TyzzyT I've checked why the tests fail. If you address those changes it should pass the tests.
However, I think I might want to split `<doe>` in two parts to address this change.
```yaml
# _common.yaml
doe: "(zet[ten]|mag|mogen|doe[n]|verander[en]|maak|schakel[en]|k(a|u)n[t] (je|jij|u)|(zal|zou) (je|jij|u))"
zou: "(kan|kun|zal|zou) (je|jij|je)"
```

```yaml
# example sentence
- "[<doe>|<zou>] [de] temperatuur <naar> <temperature> [graden] [willen | kunnen] [<doe>]"
```

2023-02-07 09:00 UTC, TheFes commented on sentences/nl/fan_HassTurnOn.yaml
> +          - "Schakel [alle] <ventilator> [<naar>] in <area>"
The double `in` was correct here, please leave it in
`Schakel alle ventilatoren in in de woonkamer`

2023-02-08 18:19 UTC, TyzzyT commented
I'll close this PR and re-do it in another branch, with all feedback in mind. Thanks for all your help so far @TheFes!

2023-02-08 18:19 UTC, closed without merging